AllCops:
  Exclude:
    - Rakefile
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'node_modules/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Layout/LineLength:
  Max: 90
  Exclude:
    - lib/tasks/*
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - lib/tasks/*
    - spec/**/*
    - app/admin/**/*

Metrics/MethodLength:
  Exclude:
    - lib/tasks/*
    - spec/**/*

Metrics/AbcSize:
  Exclude:
    - lib/tasks/*
    - spec/**/*

Style/Documentation:
  Enabled: false
